/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.jackson.nullable.JsonNullable;

import java.math.BigDecimal;
import java.util.*;

/**
 * AgentsCompletionRequest
 */
@JsonPropertyOrder({
  AgentsCompletionRequest.JSON_PROPERTY_MAX_TOKENS,
  AgentsCompletionRequest.JSON_PROPERTY_STREAM,
  AgentsCompletionRequest.JSON_PROPERTY_STOP,
  AgentsCompletionRequest.JSON_PROPERTY_RANDOM_SEED,
  AgentsCompletionRequest.JSON_PROPERTY_MESSAGES,
  AgentsCompletionRequest.JSON_PROPERTY_RESPONSE_FORMAT,
  AgentsCompletionRequest.JSON_PROPERTY_TOOLS,
  AgentsCompletionRequest.JSON_PROPERTY_TOOL_CHOICE,
  AgentsCompletionRequest.JSON_PROPERTY_PRESENCE_PENALTY,
  AgentsCompletionRequest.JSON_PROPERTY_FREQUENCY_PENALTY,
  AgentsCompletionRequest.JSON_PROPERTY_N,
  AgentsCompletionRequest.JSON_PROPERTY_PREDICTION,
  AgentsCompletionRequest.JSON_PROPERTY_AGENT_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class AgentsCompletionRequest {
  public static final String JSON_PROPERTY_MAX_TOKENS = "max_tokens";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> maxTokens = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_STREAM = "stream";
  @jakarta.annotation.Nullable
  private Boolean stream = false;

  public static final String JSON_PROPERTY_STOP = "stop";
  @jakarta.annotation.Nullable
  private Stop stop;

  public static final String JSON_PROPERTY_RANDOM_SEED = "random_seed";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> randomSeed = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @jakarta.annotation.Nonnull
  private List<MessagesInner> messages = new ArrayList<>();

  public static final String JSON_PROPERTY_RESPONSE_FORMAT = "response_format";
  @jakarta.annotation.Nullable
  private ResponseFormat responseFormat;

  public static final String JSON_PROPERTY_TOOLS = "tools";
  @jakarta.annotation.Nullable
  private JsonNullable<List<Tool>> tools = JsonNullable.<List<Tool>>undefined();

  public static final String JSON_PROPERTY_TOOL_CHOICE = "tool_choice";
  @jakarta.annotation.Nullable
  private ToolChoice toolChoice ;

  public static final String JSON_PROPERTY_PRESENCE_PENALTY = "presence_penalty";
  @jakarta.annotation.Nullable
  private BigDecimal presencePenalty = new BigDecimal("0");

  public static final String JSON_PROPERTY_FREQUENCY_PENALTY = "frequency_penalty";
  @jakarta.annotation.Nullable
  private BigDecimal frequencyPenalty = new BigDecimal("0");

  public static final String JSON_PROPERTY_N = "n";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> n = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PREDICTION = "prediction";
  @jakarta.annotation.Nullable
  private Prediction prediction;

  public static final String JSON_PROPERTY_AGENT_ID = "agent_id";
  @jakarta.annotation.Nonnull
  private String agentId;

  public AgentsCompletionRequest() {
  }

  public AgentsCompletionRequest maxTokens(@jakarta.annotation.Nullable Integer maxTokens) {
    this.maxTokens = JsonNullable.<Integer>of(maxTokens);
    
    return this;
  }

  /**
   * Get maxTokens
   * minimum: 0
   * @return maxTokens
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getMaxTokens() {
        return maxTokens.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MAX_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getMaxTokens_JsonNullable() {
    return maxTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_MAX_TOKENS)
  public void setMaxTokens_JsonNullable(JsonNullable<Integer> maxTokens) {
    this.maxTokens = maxTokens;
  }

  public void setMaxTokens(@jakarta.annotation.Nullable Integer maxTokens) {
    this.maxTokens = JsonNullable.<Integer>of(maxTokens);
  }

  public AgentsCompletionRequest stream(@jakarta.annotation.Nullable Boolean stream) {
    
    this.stream = stream;
    return this;
  }

  /**
   * Whether to stream back partial progress. If set, tokens will be sent as data-only server-side events as they become available, with the stream terminated by a data: [DONE] message. Otherwise, the server will hold the request open until the timeout or until completion, with the response containing the full result as JSON.
   * @return stream
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getStream() {
    return stream;
  }


  @JsonProperty(JSON_PROPERTY_STREAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStream(@jakarta.annotation.Nullable Boolean stream) {
    this.stream = stream;
  }

  public AgentsCompletionRequest stop(@jakarta.annotation.Nullable Stop stop) {
    
    this.stop = stop;
    return this;
  }

  /**
   * Get stop
   * @return stop
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Stop getStop() {
    return stop;
  }


  @JsonProperty(JSON_PROPERTY_STOP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStop(@jakarta.annotation.Nullable Stop stop) {
    this.stop = stop;
  }

  public AgentsCompletionRequest randomSeed(@jakarta.annotation.Nullable Integer randomSeed) {
    this.randomSeed = JsonNullable.<Integer>of(randomSeed);
    
    return this;
  }

  /**
   * Get randomSeed
   * minimum: 0
   * @return randomSeed
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getRandomSeed() {
        return randomSeed.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RANDOM_SEED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getRandomSeed_JsonNullable() {
    return randomSeed;
  }
  
  @JsonProperty(JSON_PROPERTY_RANDOM_SEED)
  public void setRandomSeed_JsonNullable(JsonNullable<Integer> randomSeed) {
    this.randomSeed = randomSeed;
  }

  public void setRandomSeed(@jakarta.annotation.Nullable Integer randomSeed) {
    this.randomSeed = JsonNullable.<Integer>of(randomSeed);
  }

  public AgentsCompletionRequest messages(@jakarta.annotation.Nonnull List<MessagesInner> messages) {
    
    this.messages = messages;
    return this;
  }

  public AgentsCompletionRequest addMessagesItem(MessagesInner messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * The prompt(s) to generate completions for, encoded as a list of dict with role and content.
   * @return messages
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<MessagesInner> getMessages() {
    return messages;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessages(@jakarta.annotation.Nonnull List<MessagesInner> messages) {
    this.messages = messages;
  }

  public AgentsCompletionRequest responseFormat(@jakarta.annotation.Nullable ResponseFormat responseFormat) {
    
    this.responseFormat = responseFormat;
    return this;
  }

  /**
   * Get responseFormat
   * @return responseFormat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResponseFormat getResponseFormat() {
    return responseFormat;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseFormat(@jakarta.annotation.Nullable ResponseFormat responseFormat) {
    this.responseFormat = responseFormat;
  }

  public AgentsCompletionRequest tools(@jakarta.annotation.Nullable List<Tool> tools) {
    this.tools = JsonNullable.<List<Tool>>of(tools);
    
    return this;
  }

  public AgentsCompletionRequest addToolsItem(Tool toolsItem) {
    if (this.tools == null || !this.tools.isPresent()) {
      this.tools = JsonNullable.<List<Tool>>of(new ArrayList<>());
    }
    try {
      this.tools.get().add(toolsItem);
    } catch (NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tools
   * @return tools
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<Tool> getTools() {
        return tools.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TOOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Tool>> getTools_JsonNullable() {
    return tools;
  }
  
  @JsonProperty(JSON_PROPERTY_TOOLS)
  public void setTools_JsonNullable(JsonNullable<List<Tool>> tools) {
    this.tools = tools;
  }

  public void setTools(@jakarta.annotation.Nullable List<Tool> tools) {
    this.tools = JsonNullable.<List<Tool>>of(tools);
  }

  public AgentsCompletionRequest toolChoice(@jakarta.annotation.Nullable ToolChoice toolChoice) {
    
    this.toolChoice = toolChoice;
    return this;
  }

  /**
   * Get toolChoice
   * @return toolChoice
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOOL_CHOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ToolChoice getToolChoice() {
    return toolChoice;
  }


  @JsonProperty(JSON_PROPERTY_TOOL_CHOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolChoice(@jakarta.annotation.Nullable ToolChoice toolChoice) {
    this.toolChoice = toolChoice;
  }

  public AgentsCompletionRequest presencePenalty(@jakarta.annotation.Nullable BigDecimal presencePenalty) {
    
    this.presencePenalty = presencePenalty;
    return this;
  }

  /**
   * presence_penalty determines how much the model penalizes the repetition of words or phrases. A higher presence penalty encourages the model to use a wider variety of words and phrases, making the output more diverse and creative.
   * minimum: -2
   * maximum: 2
   * @return presencePenalty
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRESENCE_PENALTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPresencePenalty() {
    return presencePenalty;
  }


  @JsonProperty(JSON_PROPERTY_PRESENCE_PENALTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPresencePenalty(@jakarta.annotation.Nullable BigDecimal presencePenalty) {
    this.presencePenalty = presencePenalty;
  }

  public AgentsCompletionRequest frequencyPenalty(@jakarta.annotation.Nullable BigDecimal frequencyPenalty) {
    
    this.frequencyPenalty = frequencyPenalty;
    return this;
  }

  /**
   * frequency_penalty penalizes the repetition of words based on their frequency in the generated text. A higher frequency penalty discourages the model from repeating words that have already appeared frequently in the output, promoting diversity and reducing repetition.
   * minimum: -2
   * maximum: 2
   * @return frequencyPenalty
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FREQUENCY_PENALTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFrequencyPenalty() {
    return frequencyPenalty;
  }


  @JsonProperty(JSON_PROPERTY_FREQUENCY_PENALTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrequencyPenalty(@jakarta.annotation.Nullable BigDecimal frequencyPenalty) {
    this.frequencyPenalty = frequencyPenalty;
  }

  public AgentsCompletionRequest n(@jakarta.annotation.Nullable Integer n) {
    this.n = JsonNullable.<Integer>of(n);
    
    return this;
  }

  /**
   * Get n
   * minimum: 1
   * @return n
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getN() {
        return n.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getN_JsonNullable() {
    return n;
  }
  
  @JsonProperty(JSON_PROPERTY_N)
  public void setN_JsonNullable(JsonNullable<Integer> n) {
    this.n = n;
  }

  public void setN(@jakarta.annotation.Nullable Integer n) {
    this.n = JsonNullable.<Integer>of(n);
  }

  public AgentsCompletionRequest prediction(@jakarta.annotation.Nullable Prediction prediction) {
    
    this.prediction = prediction;
    return this;
  }

  /**
   * Get prediction
   * @return prediction
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREDICTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Prediction getPrediction() {
    return prediction;
  }


  @JsonProperty(JSON_PROPERTY_PREDICTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrediction(@jakarta.annotation.Nullable Prediction prediction) {
    this.prediction = prediction;
  }

  public AgentsCompletionRequest agentId(@jakarta.annotation.Nonnull String agentId) {
    
    this.agentId = agentId;
    return this;
  }

  /**
   * The ID of the agent to use for this completion.
   * @return agentId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AGENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgentId() {
    return agentId;
  }


  @JsonProperty(JSON_PROPERTY_AGENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgentId(@jakarta.annotation.Nonnull String agentId) {
    this.agentId = agentId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentsCompletionRequest agentsCompletionRequest = (AgentsCompletionRequest) o;
    return equalsNullable(this.maxTokens, agentsCompletionRequest.maxTokens) &&
        Objects.equals(this.stream, agentsCompletionRequest.stream) &&
        Objects.equals(this.stop, agentsCompletionRequest.stop) &&
        equalsNullable(this.randomSeed, agentsCompletionRequest.randomSeed) &&
        Objects.equals(this.messages, agentsCompletionRequest.messages) &&
        Objects.equals(this.responseFormat, agentsCompletionRequest.responseFormat) &&
        equalsNullable(this.tools, agentsCompletionRequest.tools) &&
        Objects.equals(this.toolChoice, agentsCompletionRequest.toolChoice) &&
        Objects.equals(this.presencePenalty, agentsCompletionRequest.presencePenalty) &&
        Objects.equals(this.frequencyPenalty, agentsCompletionRequest.frequencyPenalty) &&
        equalsNullable(this.n, agentsCompletionRequest.n) &&
        Objects.equals(this.prediction, agentsCompletionRequest.prediction) &&
        Objects.equals(this.agentId, agentsCompletionRequest.agentId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(maxTokens), stream, stop, hashCodeNullable(randomSeed), messages, responseFormat, hashCodeNullable(tools), toolChoice, presencePenalty, frequencyPenalty, hashCodeNullable(n), prediction, agentId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentsCompletionRequest {\n");
    sb.append("    maxTokens: ").append(toIndentedString(maxTokens)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    stop: ").append(toIndentedString(stop)).append("\n");
    sb.append("    randomSeed: ").append(toIndentedString(randomSeed)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("    toolChoice: ").append(toIndentedString(toolChoice)).append("\n");
    sb.append("    presencePenalty: ").append(toIndentedString(presencePenalty)).append("\n");
    sb.append("    frequencyPenalty: ").append(toIndentedString(frequencyPenalty)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    prediction: ").append(toIndentedString(prediction)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

