/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.*;
import org.openapitools.jackson.nullable.JsonNullable;

import java.util.*;

/**
 * AssistantMessage
 */
@JsonPropertyOrder({
  AssistantMessage.JSON_PROPERTY_CONTENT,
  AssistantMessage.JSON_PROPERTY_TOOL_CALLS,
  AssistantMessage.JSON_PROPERTY_PREFIX,
  AssistantMessage.JSON_PROPERTY_ROLE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class AssistantMessage {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @jakarta.annotation.Nullable
  private JsonNullable<Content> content = JsonNullable.<Content>undefined();

  public static final String JSON_PROPERTY_TOOL_CALLS = "tool_calls";
  @jakarta.annotation.Nullable
  private JsonNullable<List<ToolCall>> toolCalls = JsonNullable.<List<ToolCall>>undefined();

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @jakarta.annotation.Nullable
  private Boolean prefix = false;

  /**
   * Gets or Sets role
   */
  public enum RoleEnum {
    ASSISTANT(String.valueOf("assistant"));

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ROLE = "role";
  @jakarta.annotation.Nullable
  private RoleEnum role = RoleEnum.ASSISTANT;

  public AssistantMessage() {
  }

  public AssistantMessage content(@jakarta.annotation.Nullable Content content) {
    this.content = JsonNullable.<Content>of(content);
    
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Content getContent() {
        return content.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Content> getContent_JsonNullable() {
    return content;
  }
  
  @JsonProperty(JSON_PROPERTY_CONTENT)
  public void setContent_JsonNullable(JsonNullable<Content> content) {
    this.content = content;
  }

  public void setContent(@jakarta.annotation.Nullable Content content) {
    this.content = JsonNullable.<Content>of(content);
  }

  public AssistantMessage toolCalls(@jakarta.annotation.Nullable List<ToolCall> toolCalls) {
    this.toolCalls = JsonNullable.<List<ToolCall>>of(toolCalls);
    
    return this;
  }

  public AssistantMessage addToolCallsItem(ToolCall toolCallsItem) {
    if (this.toolCalls == null || !this.toolCalls.isPresent()) {
      this.toolCalls = JsonNullable.<List<ToolCall>>of(new ArrayList<>());
    }
    try {
      this.toolCalls.get().add(toolCallsItem);
    } catch (NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get toolCalls
   * @return toolCalls
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<ToolCall> getToolCalls() {
        return toolCalls.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TOOL_CALLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<ToolCall>> getToolCalls_JsonNullable() {
    return toolCalls;
  }
  
  @JsonProperty(JSON_PROPERTY_TOOL_CALLS)
  public void setToolCalls_JsonNullable(JsonNullable<List<ToolCall>> toolCalls) {
    this.toolCalls = toolCalls;
  }

  public void setToolCalls(@jakarta.annotation.Nullable List<ToolCall> toolCalls) {
    this.toolCalls = JsonNullable.<List<ToolCall>>of(toolCalls);
  }

  public AssistantMessage prefix(@jakarta.annotation.Nullable Boolean prefix) {
    
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPrefix() {
    return prefix;
  }


  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrefix(@jakarta.annotation.Nullable Boolean prefix) {
    this.prefix = prefix;
  }

  public AssistantMessage role(@jakarta.annotation.Nullable RoleEnum role) {
    
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RoleEnum getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(@jakarta.annotation.Nullable RoleEnum role) {
    this.role = role;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssistantMessage assistantMessage = (AssistantMessage) o;
    return equalsNullable(this.content, assistantMessage.content) &&
        equalsNullable(this.toolCalls, assistantMessage.toolCalls) &&
        Objects.equals(this.prefix, assistantMessage.prefix) &&
        Objects.equals(this.role, assistantMessage.role);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(content), hashCodeNullable(toolCalls), prefix, role);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssistantMessage {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    toolCalls: ").append(toIndentedString(toolCalls)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

