/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ContentChunk
 */
@JsonPropertyOrder({
  ContentChunk.JSON_PROPERTY_TEXT,
  ContentChunk.JSON_PROPERTY_TYPE,
  ContentChunk.JSON_PROPERTY_IMAGE_URL,
  ContentChunk.JSON_PROPERTY_REFERENCE_IDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ImageURLChunk.class, name = "image_url"),
  @JsonSubTypes.Type(value = ReferenceChunk.class, name = "reference"),
  @JsonSubTypes.Type(value = TextChunk.class, name = "text"),
  @JsonSubTypes.Type(value = ImageURLChunk.class, name = "ImageURLChunk"),
  @JsonSubTypes.Type(value = ReferenceChunk.class, name = "ReferenceChunk"),
  @JsonSubTypes.Type(value = TextChunk.class, name = "TextChunk"),
})

public class ContentChunk {
  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nonnull
  private String text;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TEXT(String.valueOf("text")),
    
    IMAGE_URL(String.valueOf("image_url")),
    
    REFERENCE(String.valueOf("reference"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type = TypeEnum.TEXT;

  public static final String JSON_PROPERTY_IMAGE_URL = "image_url";
  @jakarta.annotation.Nonnull
  private ImageUrl imageUrl;

  public static final String JSON_PROPERTY_REFERENCE_IDS = "reference_ids";
  @jakarta.annotation.Nonnull
  private List<Integer> referenceIds = new ArrayList<>();

  public ContentChunk() {
  }

  public ContentChunk text(@jakarta.annotation.Nonnull String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@jakarta.annotation.Nonnull String text) {
    this.text = text;
  }

  public ContentChunk type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public ContentChunk imageUrl(@jakarta.annotation.Nonnull ImageUrl imageUrl) {
    
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * Get imageUrl
   * @return imageUrl
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IMAGE_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ImageUrl getImageUrl() {
    return imageUrl;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setImageUrl(@jakarta.annotation.Nonnull ImageUrl imageUrl) {
    this.imageUrl = imageUrl;
  }

  public ContentChunk referenceIds(@jakarta.annotation.Nonnull List<Integer> referenceIds) {
    
    this.referenceIds = referenceIds;
    return this;
  }

  public ContentChunk addReferenceIdsItem(Integer referenceIdsItem) {
    if (this.referenceIds == null) {
      this.referenceIds = new ArrayList<>();
    }
    this.referenceIds.add(referenceIdsItem);
    return this;
  }

  /**
   * Get referenceIds
   * @return referenceIds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REFERENCE_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Integer> getReferenceIds() {
    return referenceIds;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferenceIds(@jakarta.annotation.Nonnull List<Integer> referenceIds) {
    this.referenceIds = referenceIds;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentChunk contentChunk = (ContentChunk) o;
    return Objects.equals(this.text, contentChunk.text) &&
        Objects.equals(this.type, contentChunk.type) &&
        Objects.equals(this.imageUrl, contentChunk.imageUrl) &&
        Objects.equals(this.referenceIds, contentChunk.referenceIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, type, imageUrl, referenceIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentChunk {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    referenceIds: ").append(toIndentedString(referenceIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

