/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.*;
import org.openapitools.jackson.nullable.JsonNullable;

import java.util.*;

/**
 * DetailedJobOut
 */
@JsonPropertyOrder({
  DetailedJobOut.JSON_PROPERTY_ID,
  DetailedJobOut.JSON_PROPERTY_AUTO_START,
  DetailedJobOut.JSON_PROPERTY_HYPERPARAMETERS,
  DetailedJobOut.JSON_PROPERTY_MODEL,
  DetailedJobOut.JSON_PROPERTY_STATUS,
  DetailedJobOut.JSON_PROPERTY_JOB_TYPE,
  DetailedJobOut.JSON_PROPERTY_CREATED_AT,
  DetailedJobOut.JSON_PROPERTY_MODIFIED_AT,
  DetailedJobOut.JSON_PROPERTY_TRAINING_FILES,
  DetailedJobOut.JSON_PROPERTY_VALIDATION_FILES,
  DetailedJobOut.JSON_PROPERTY_OBJECT,
  DetailedJobOut.JSON_PROPERTY_FINE_TUNED_MODEL,
  DetailedJobOut.JSON_PROPERTY_SUFFIX,
  DetailedJobOut.JSON_PROPERTY_INTEGRATIONS,
  DetailedJobOut.JSON_PROPERTY_TRAINED_TOKENS,
  DetailedJobOut.JSON_PROPERTY_REPOSITORIES,
  DetailedJobOut.JSON_PROPERTY_METADATA,
  DetailedJobOut.JSON_PROPERTY_EVENTS,
  DetailedJobOut.JSON_PROPERTY_CHECKPOINTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class DetailedJobOut {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_AUTO_START = "auto_start";
  @jakarta.annotation.Nonnull
  private Boolean autoStart;

  public static final String JSON_PROPERTY_HYPERPARAMETERS = "hyperparameters";
  @jakarta.annotation.Nonnull
  private TrainingParameters hyperparameters;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nonnull
  private FineTuneableModel model;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    QUEUED(String.valueOf("QUEUED")),
    
    STARTED(String.valueOf("STARTED")),
    
    VALIDATING(String.valueOf("VALIDATING")),
    
    VALIDATED(String.valueOf("VALIDATED")),
    
    RUNNING(String.valueOf("RUNNING")),
    
    FAILED_VALIDATION(String.valueOf("FAILED_VALIDATION")),
    
    FAILED(String.valueOf("FAILED")),
    
    SUCCESS(String.valueOf("SUCCESS")),
    
    CANCELLED(String.valueOf("CANCELLED")),
    
    CANCELLATION_REQUESTED(String.valueOf("CANCELLATION_REQUESTED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_JOB_TYPE = "job_type";
  @jakarta.annotation.Nonnull
  private String jobType;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nonnull
  private Integer createdAt;

  public static final String JSON_PROPERTY_MODIFIED_AT = "modified_at";
  @jakarta.annotation.Nonnull
  private Integer modifiedAt;

  public static final String JSON_PROPERTY_TRAINING_FILES = "training_files";
  @jakarta.annotation.Nonnull
  private List<UUID> trainingFiles = new ArrayList<>();

  public static final String JSON_PROPERTY_VALIDATION_FILES = "validation_files";
  @jakarta.annotation.Nullable
  private JsonNullable<List<UUID>> validationFiles = JsonNullable.<List<UUID>>undefined();

  /**
   * Gets or Sets _object
   */
  public enum ObjectEnum {
    JOB(String.valueOf("job"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @jakarta.annotation.Nullable
  private ObjectEnum _object = ObjectEnum.JOB;

  public static final String JSON_PROPERTY_FINE_TUNED_MODEL = "fine_tuned_model";
  @jakarta.annotation.Nullable
  private JsonNullable<String> fineTunedModel = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SUFFIX = "suffix";
  @jakarta.annotation.Nullable
  private JsonNullable<String> suffix = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INTEGRATIONS = "integrations";
  @jakarta.annotation.Nullable
  private JsonNullable<List<JobOutIntegrationsInner>> integrations = JsonNullable.<List<JobOutIntegrationsInner>>undefined();

  public static final String JSON_PROPERTY_TRAINED_TOKENS = "trained_tokens";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> trainedTokens = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_REPOSITORIES = "repositories";
  @jakarta.annotation.Nullable
  private List<RepositoriesInner> repositories = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private JsonNullable<JobMetadataOut> metadata = JsonNullable.<JobMetadataOut>undefined();

  public static final String JSON_PROPERTY_EVENTS = "events";
  @jakarta.annotation.Nullable
  private List<EventOut> events = new ArrayList<>();

  public static final String JSON_PROPERTY_CHECKPOINTS = "checkpoints";
  @jakarta.annotation.Nullable
  private List<CheckpointOut> checkpoints = new ArrayList<>();

  public DetailedJobOut() {
  }

  public DetailedJobOut id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public DetailedJobOut autoStart(@jakarta.annotation.Nonnull Boolean autoStart) {
    
    this.autoStart = autoStart;
    return this;
  }

  /**
   * Get autoStart
   * @return autoStart
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AUTO_START)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAutoStart() {
    return autoStart;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_START)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAutoStart(@jakarta.annotation.Nonnull Boolean autoStart) {
    this.autoStart = autoStart;
  }

  public DetailedJobOut hyperparameters(@jakarta.annotation.Nonnull TrainingParameters hyperparameters) {
    
    this.hyperparameters = hyperparameters;
    return this;
  }

  /**
   * Get hyperparameters
   * @return hyperparameters
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HYPERPARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TrainingParameters getHyperparameters() {
    return hyperparameters;
  }


  @JsonProperty(JSON_PROPERTY_HYPERPARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHyperparameters(@jakarta.annotation.Nonnull TrainingParameters hyperparameters) {
    this.hyperparameters = hyperparameters;
  }

  public DetailedJobOut model(@jakarta.annotation.Nonnull FineTuneableModel model) {
    
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FineTuneableModel getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@jakarta.annotation.Nonnull FineTuneableModel model) {
    this.model = model;
  }

  public DetailedJobOut status(@jakarta.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public DetailedJobOut jobType(@jakarta.annotation.Nonnull String jobType) {
    
    this.jobType = jobType;
    return this;
  }

  /**
   * Get jobType
   * @return jobType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getJobType() {
    return jobType;
  }


  @JsonProperty(JSON_PROPERTY_JOB_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJobType(@jakarta.annotation.Nonnull String jobType) {
    this.jobType = jobType;
  }

  public DetailedJobOut createdAt(@jakarta.annotation.Nonnull Integer createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull Integer createdAt) {
    this.createdAt = createdAt;
  }

  public DetailedJobOut modifiedAt(@jakarta.annotation.Nonnull Integer modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

  /**
   * Get modifiedAt
   * @return modifiedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getModifiedAt() {
    return modifiedAt;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedAt(@jakarta.annotation.Nonnull Integer modifiedAt) {
    this.modifiedAt = modifiedAt;
  }

  public DetailedJobOut trainingFiles(@jakarta.annotation.Nonnull List<UUID> trainingFiles) {
    
    this.trainingFiles = trainingFiles;
    return this;
  }

  public DetailedJobOut addTrainingFilesItem(UUID trainingFilesItem) {
    if (this.trainingFiles == null) {
      this.trainingFiles = new ArrayList<>();
    }
    this.trainingFiles.add(trainingFilesItem);
    return this;
  }

  /**
   * Get trainingFiles
   * @return trainingFiles
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRAINING_FILES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<UUID> getTrainingFiles() {
    return trainingFiles;
  }


  @JsonProperty(JSON_PROPERTY_TRAINING_FILES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainingFiles(@jakarta.annotation.Nonnull List<UUID> trainingFiles) {
    this.trainingFiles = trainingFiles;
  }

  public DetailedJobOut validationFiles(@jakarta.annotation.Nullable List<UUID> validationFiles) {
    this.validationFiles = JsonNullable.<List<UUID>>of(validationFiles);
    
    return this;
  }

  public DetailedJobOut addValidationFilesItem(UUID validationFilesItem) {
    if (this.validationFiles == null || !this.validationFiles.isPresent()) {
      this.validationFiles = JsonNullable.<List<UUID>>of(new ArrayList<>());
    }
    try {
      this.validationFiles.get().add(validationFilesItem);
    } catch (NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get validationFiles
   * @return validationFiles
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<UUID> getValidationFiles() {
        return validationFiles.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VALIDATION_FILES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<UUID>> getValidationFiles_JsonNullable() {
    return validationFiles;
  }
  
  @JsonProperty(JSON_PROPERTY_VALIDATION_FILES)
  public void setValidationFiles_JsonNullable(JsonNullable<List<UUID>> validationFiles) {
    this.validationFiles = validationFiles;
  }

  public void setValidationFiles(@jakarta.annotation.Nullable List<UUID> validationFiles) {
    this.validationFiles = JsonNullable.<List<UUID>>of(validationFiles);
  }

  public DetailedJobOut _object(@jakarta.annotation.Nullable ObjectEnum _object) {
    
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@jakarta.annotation.Nullable ObjectEnum _object) {
    this._object = _object;
  }

  public DetailedJobOut fineTunedModel(@jakarta.annotation.Nullable String fineTunedModel) {
    this.fineTunedModel = JsonNullable.<String>of(fineTunedModel);
    
    return this;
  }

  /**
   * Get fineTunedModel
   * @return fineTunedModel
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getFineTunedModel() {
        return fineTunedModel.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FINE_TUNED_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFineTunedModel_JsonNullable() {
    return fineTunedModel;
  }
  
  @JsonProperty(JSON_PROPERTY_FINE_TUNED_MODEL)
  public void setFineTunedModel_JsonNullable(JsonNullable<String> fineTunedModel) {
    this.fineTunedModel = fineTunedModel;
  }

  public void setFineTunedModel(@jakarta.annotation.Nullable String fineTunedModel) {
    this.fineTunedModel = JsonNullable.<String>of(fineTunedModel);
  }

  public DetailedJobOut suffix(@jakarta.annotation.Nullable String suffix) {
    this.suffix = JsonNullable.<String>of(suffix);
    
    return this;
  }

  /**
   * Get suffix
   * @return suffix
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSuffix() {
        return suffix.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SUFFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSuffix_JsonNullable() {
    return suffix;
  }
  
  @JsonProperty(JSON_PROPERTY_SUFFIX)
  public void setSuffix_JsonNullable(JsonNullable<String> suffix) {
    this.suffix = suffix;
  }

  public void setSuffix(@jakarta.annotation.Nullable String suffix) {
    this.suffix = JsonNullable.<String>of(suffix);
  }

  public DetailedJobOut integrations(@jakarta.annotation.Nullable List<JobOutIntegrationsInner> integrations) {
    this.integrations = JsonNullable.<List<JobOutIntegrationsInner>>of(integrations);
    
    return this;
  }

  public DetailedJobOut addIntegrationsItem(JobOutIntegrationsInner integrationsItem) {
    if (this.integrations == null || !this.integrations.isPresent()) {
      this.integrations = JsonNullable.<List<JobOutIntegrationsInner>>of(new ArrayList<>());
    }
    try {
      this.integrations.get().add(integrationsItem);
    } catch (NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get integrations
   * @return integrations
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<JobOutIntegrationsInner> getIntegrations() {
        return integrations.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INTEGRATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<JobOutIntegrationsInner>> getIntegrations_JsonNullable() {
    return integrations;
  }
  
  @JsonProperty(JSON_PROPERTY_INTEGRATIONS)
  public void setIntegrations_JsonNullable(JsonNullable<List<JobOutIntegrationsInner>> integrations) {
    this.integrations = integrations;
  }

  public void setIntegrations(@jakarta.annotation.Nullable List<JobOutIntegrationsInner> integrations) {
    this.integrations = JsonNullable.<List<JobOutIntegrationsInner>>of(integrations);
  }

  public DetailedJobOut trainedTokens(@jakarta.annotation.Nullable Integer trainedTokens) {
    this.trainedTokens = JsonNullable.<Integer>of(trainedTokens);
    
    return this;
  }

  /**
   * Get trainedTokens
   * @return trainedTokens
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getTrainedTokens() {
        return trainedTokens.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRAINED_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTrainedTokens_JsonNullable() {
    return trainedTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_TRAINED_TOKENS)
  public void setTrainedTokens_JsonNullable(JsonNullable<Integer> trainedTokens) {
    this.trainedTokens = trainedTokens;
  }

  public void setTrainedTokens(@jakarta.annotation.Nullable Integer trainedTokens) {
    this.trainedTokens = JsonNullable.<Integer>of(trainedTokens);
  }

  public DetailedJobOut repositories(@jakarta.annotation.Nullable List<RepositoriesInner> repositories) {
    
    this.repositories = repositories;
    return this;
  }

  public DetailedJobOut addRepositoriesItem(RepositoriesInner repositoriesItem) {
    if (this.repositories == null) {
      this.repositories = new ArrayList<>();
    }
    this.repositories.add(repositoriesItem);
    return this;
  }

  /**
   * Get repositories
   * @return repositories
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPOSITORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RepositoriesInner> getRepositories() {
    return repositories;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepositories(@jakarta.annotation.Nullable List<RepositoriesInner> repositories) {
    this.repositories = repositories;
  }

  public DetailedJobOut metadata(@jakarta.annotation.Nullable JobMetadataOut metadata) {
    this.metadata = JsonNullable.<JobMetadataOut>of(metadata);
    
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public JobMetadataOut getMetadata() {
        return metadata.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<JobMetadataOut> getMetadata_JsonNullable() {
    return metadata;
  }
  
  @JsonProperty(JSON_PROPERTY_METADATA)
  public void setMetadata_JsonNullable(JsonNullable<JobMetadataOut> metadata) {
    this.metadata = metadata;
  }

  public void setMetadata(@jakarta.annotation.Nullable JobMetadataOut metadata) {
    this.metadata = JsonNullable.<JobMetadataOut>of(metadata);
  }

  public DetailedJobOut events(@jakarta.annotation.Nullable List<EventOut> events) {
    
    this.events = events;
    return this;
  }

  public DetailedJobOut addEventsItem(EventOut eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Event items are created every time the status of a fine-tuning job changes. The timestamped list of all events is accessible here.
   * @return events
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EventOut> getEvents() {
    return events;
  }


  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvents(@jakarta.annotation.Nullable List<EventOut> events) {
    this.events = events;
  }

  public DetailedJobOut checkpoints(@jakarta.annotation.Nullable List<CheckpointOut> checkpoints) {
    
    this.checkpoints = checkpoints;
    return this;
  }

  public DetailedJobOut addCheckpointsItem(CheckpointOut checkpointsItem) {
    if (this.checkpoints == null) {
      this.checkpoints = new ArrayList<>();
    }
    this.checkpoints.add(checkpointsItem);
    return this;
  }

  /**
   * Get checkpoints
   * @return checkpoints
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECKPOINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CheckpointOut> getCheckpoints() {
    return checkpoints;
  }


  @JsonProperty(JSON_PROPERTY_CHECKPOINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckpoints(@jakarta.annotation.Nullable List<CheckpointOut> checkpoints) {
    this.checkpoints = checkpoints;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedJobOut detailedJobOut = (DetailedJobOut) o;
    return Objects.equals(this.id, detailedJobOut.id) &&
        Objects.equals(this.autoStart, detailedJobOut.autoStart) &&
        Objects.equals(this.hyperparameters, detailedJobOut.hyperparameters) &&
        Objects.equals(this.model, detailedJobOut.model) &&
        Objects.equals(this.status, detailedJobOut.status) &&
        Objects.equals(this.jobType, detailedJobOut.jobType) &&
        Objects.equals(this.createdAt, detailedJobOut.createdAt) &&
        Objects.equals(this.modifiedAt, detailedJobOut.modifiedAt) &&
        Objects.equals(this.trainingFiles, detailedJobOut.trainingFiles) &&
        equalsNullable(this.validationFiles, detailedJobOut.validationFiles) &&
        Objects.equals(this._object, detailedJobOut._object) &&
        equalsNullable(this.fineTunedModel, detailedJobOut.fineTunedModel) &&
        equalsNullable(this.suffix, detailedJobOut.suffix) &&
        equalsNullable(this.integrations, detailedJobOut.integrations) &&
        equalsNullable(this.trainedTokens, detailedJobOut.trainedTokens) &&
        Objects.equals(this.repositories, detailedJobOut.repositories) &&
        equalsNullable(this.metadata, detailedJobOut.metadata) &&
        Objects.equals(this.events, detailedJobOut.events) &&
        Objects.equals(this.checkpoints, detailedJobOut.checkpoints);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, autoStart, hyperparameters, model, status, jobType, createdAt, modifiedAt, trainingFiles, hashCodeNullable(validationFiles), _object, hashCodeNullable(fineTunedModel), hashCodeNullable(suffix), hashCodeNullable(integrations), hashCodeNullable(trainedTokens), repositories, hashCodeNullable(metadata), events, checkpoints);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedJobOut {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    autoStart: ").append(toIndentedString(autoStart)).append("\n");
    sb.append("    hyperparameters: ").append(toIndentedString(hyperparameters)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    jobType: ").append(toIndentedString(jobType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    trainingFiles: ").append(toIndentedString(trainingFiles)).append("\n");
    sb.append("    validationFiles: ").append(toIndentedString(validationFiles)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    fineTunedModel: ").append(toIndentedString(fineTunedModel)).append("\n");
    sb.append("    suffix: ").append(toIndentedString(suffix)).append("\n");
    sb.append("    integrations: ").append(toIndentedString(integrations)).append("\n");
    sb.append("    trainedTokens: ").append(toIndentedString(trainedTokens)).append("\n");
    sb.append("    repositories: ").append(toIndentedString(repositories)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    checkpoints: ").append(toIndentedString(checkpoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

