/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EmbeddingResponseData
 */
@JsonPropertyOrder({
  EmbeddingResponseData.JSON_PROPERTY_OBJECT,
  EmbeddingResponseData.JSON_PROPERTY_EMBEDDING,
  EmbeddingResponseData.JSON_PROPERTY_INDEX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class EmbeddingResponseData {
  public static final String JSON_PROPERTY_OBJECT = "object";
  @jakarta.annotation.Nullable
  private String _object;

  public static final String JSON_PROPERTY_EMBEDDING = "embedding";
  @jakarta.annotation.Nullable
  private List<BigDecimal> embedding = new ArrayList<>();

  public static final String JSON_PROPERTY_INDEX = "index";
  @jakarta.annotation.Nullable
  private Integer index;

  public EmbeddingResponseData() {
  }

  public EmbeddingResponseData _object(@jakarta.annotation.Nullable String _object) {
    
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@jakarta.annotation.Nullable String _object) {
    this._object = _object;
  }

  public EmbeddingResponseData embedding(@jakarta.annotation.Nullable List<BigDecimal> embedding) {
    
    this.embedding = embedding;
    return this;
  }

  public EmbeddingResponseData addEmbeddingItem(BigDecimal embeddingItem) {
    if (this.embedding == null) {
      this.embedding = new ArrayList<>();
    }
    this.embedding.add(embeddingItem);
    return this;
  }

  /**
   * Get embedding
   * @return embedding
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMBEDDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BigDecimal> getEmbedding() {
    return embedding;
  }


  @JsonProperty(JSON_PROPERTY_EMBEDDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmbedding(@jakarta.annotation.Nullable List<BigDecimal> embedding) {
    this.embedding = embedding;
  }

  public EmbeddingResponseData index(@jakarta.annotation.Nullable Integer index) {
    
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIndex() {
    return index;
  }


  @JsonProperty(JSON_PROPERTY_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndex(@jakarta.annotation.Nullable Integer index) {
    this.index = index;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddingResponseData embeddingResponseData = (EmbeddingResponseData) o;
    return Objects.equals(this._object, embeddingResponseData._object) &&
        Objects.equals(this.embedding, embeddingResponseData.embedding) &&
        Objects.equals(this.index, embeddingResponseData.index);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_object, embedding, index);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddingResponseData {\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    embedding: ").append(toIndentedString(embedding)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

