/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The name of the model to fine-tune.
 */
public enum FineTuneableModel {
  
  OPEN_MISTRAL_7B("open-mistral-7b"),
  
  MISTRAL_SMALL_LATEST("mistral-small-latest"),
  
  CODESTRAL_LATEST("codestral-latest"),
  
  MISTRAL_LARGE_LATEST("mistral-large-latest"),
  
  OPEN_MISTRAL_NEMO("open-mistral-nemo"),
  
  MINISTRAL_3B_LATEST("ministral-3b-latest");

  private String value;

  FineTuneableModel(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static FineTuneableModel fromValue(String value) {
    for (FineTuneableModel b : FineTuneableModel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

