/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * FTModelCapabilitiesOut
 */
@JsonPropertyOrder({
  FTModelCapabilitiesOut.JSON_PROPERTY_COMPLETION_CHAT,
  FTModelCapabilitiesOut.JSON_PROPERTY_COMPLETION_FIM,
  FTModelCapabilitiesOut.JSON_PROPERTY_FUNCTION_CALLING,
  FTModelCapabilitiesOut.JSON_PROPERTY_FINE_TUNING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class FTModelCapabilitiesOut {
  public static final String JSON_PROPERTY_COMPLETION_CHAT = "completion_chat";
  @jakarta.annotation.Nullable
  private Boolean completionChat = true;

  public static final String JSON_PROPERTY_COMPLETION_FIM = "completion_fim";
  @jakarta.annotation.Nullable
  private Boolean completionFim = false;

  public static final String JSON_PROPERTY_FUNCTION_CALLING = "function_calling";
  @jakarta.annotation.Nullable
  private Boolean functionCalling = false;

  public static final String JSON_PROPERTY_FINE_TUNING = "fine_tuning";
  @jakarta.annotation.Nullable
  private Boolean fineTuning = false;

  public FTModelCapabilitiesOut() {
  }

  public FTModelCapabilitiesOut completionChat(@jakarta.annotation.Nullable Boolean completionChat) {
    
    this.completionChat = completionChat;
    return this;
  }

  /**
   * Get completionChat
   * @return completionChat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLETION_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCompletionChat() {
    return completionChat;
  }


  @JsonProperty(JSON_PROPERTY_COMPLETION_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompletionChat(@jakarta.annotation.Nullable Boolean completionChat) {
    this.completionChat = completionChat;
  }

  public FTModelCapabilitiesOut completionFim(@jakarta.annotation.Nullable Boolean completionFim) {
    
    this.completionFim = completionFim;
    return this;
  }

  /**
   * Get completionFim
   * @return completionFim
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLETION_FIM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCompletionFim() {
    return completionFim;
  }


  @JsonProperty(JSON_PROPERTY_COMPLETION_FIM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompletionFim(@jakarta.annotation.Nullable Boolean completionFim) {
    this.completionFim = completionFim;
  }

  public FTModelCapabilitiesOut functionCalling(@jakarta.annotation.Nullable Boolean functionCalling) {
    
    this.functionCalling = functionCalling;
    return this;
  }

  /**
   * Get functionCalling
   * @return functionCalling
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTION_CALLING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFunctionCalling() {
    return functionCalling;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION_CALLING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunctionCalling(@jakarta.annotation.Nullable Boolean functionCalling) {
    this.functionCalling = functionCalling;
  }

  public FTModelCapabilitiesOut fineTuning(@jakarta.annotation.Nullable Boolean fineTuning) {
    
    this.fineTuning = fineTuning;
    return this;
  }

  /**
   * Get fineTuning
   * @return fineTuning
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINE_TUNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFineTuning() {
    return fineTuning;
  }


  @JsonProperty(JSON_PROPERTY_FINE_TUNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFineTuning(@jakarta.annotation.Nullable Boolean fineTuning) {
    this.fineTuning = fineTuning;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FTModelCapabilitiesOut ftModelCapabilitiesOut = (FTModelCapabilitiesOut) o;
    return Objects.equals(this.completionChat, ftModelCapabilitiesOut.completionChat) &&
        Objects.equals(this.completionFim, ftModelCapabilitiesOut.completionFim) &&
        Objects.equals(this.functionCalling, ftModelCapabilitiesOut.functionCalling) &&
        Objects.equals(this.fineTuning, ftModelCapabilitiesOut.fineTuning);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completionChat, completionFim, functionCalling, fineTuning);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FTModelCapabilitiesOut {\n");
    sb.append("    completionChat: ").append(toIndentedString(completionChat)).append("\n");
    sb.append("    completionFim: ").append(toIndentedString(completionFim)).append("\n");
    sb.append("    functionCalling: ").append(toIndentedString(functionCalling)).append("\n");
    sb.append("    fineTuning: ").append(toIndentedString(fineTuning)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

