/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.*;
import org.openapitools.jackson.nullable.JsonNullable;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

/**
 * Extra fields for fine-tuned models.
 */
@JsonPropertyOrder({
  FTModelCard.JSON_PROPERTY_ID,
  FTModelCard.JSON_PROPERTY_OBJECT,
  FTModelCard.JSON_PROPERTY_CREATED,
  FTModelCard.JSON_PROPERTY_OWNED_BY,
  FTModelCard.JSON_PROPERTY_CAPABILITIES,
  FTModelCard.JSON_PROPERTY_NAME,
  FTModelCard.JSON_PROPERTY_DESCRIPTION,
  FTModelCard.JSON_PROPERTY_MAX_CONTEXT_LENGTH,
  FTModelCard.JSON_PROPERTY_ALIASES,
  FTModelCard.JSON_PROPERTY_DEPRECATION,
  FTModelCard.JSON_PROPERTY_DEFAULT_MODEL_TEMPERATURE,
  FTModelCard.JSON_PROPERTY_TYPE,
  FTModelCard.JSON_PROPERTY_JOB,
  FTModelCard.JSON_PROPERTY_ROOT,
  FTModelCard.JSON_PROPERTY_ARCHIVED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class FTModelCard {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_OBJECT = "object";
  @jakarta.annotation.Nullable
  private String _object = "model";

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable
  private Integer created;

  public static final String JSON_PROPERTY_OWNED_BY = "owned_by";
  @jakarta.annotation.Nullable
  private String ownedBy = "mistralai";

  public static final String JSON_PROPERTY_CAPABILITIES = "capabilities";
  @jakarta.annotation.Nonnull
  private ModelCapabilities capabilities;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MAX_CONTEXT_LENGTH = "max_context_length";
  @jakarta.annotation.Nullable
  private Integer maxContextLength = 32768;

  public static final String JSON_PROPERTY_ALIASES = "aliases";
  @jakarta.annotation.Nullable
  private List<String> aliases = new ArrayList<>();

  public static final String JSON_PROPERTY_DEPRECATION = "deprecation";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> deprecation = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_DEFAULT_MODEL_TEMPERATURE = "default_model_temperature";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> defaultModelTemperature = JsonNullable.<BigDecimal>undefined();

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    FINE_TUNED(String.valueOf("fine-tuned"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type = TypeEnum.FINE_TUNED;

  public static final String JSON_PROPERTY_JOB = "job";
  @jakarta.annotation.Nonnull
  private String job;

  public static final String JSON_PROPERTY_ROOT = "root";
  @jakarta.annotation.Nonnull
  private String root;

  public static final String JSON_PROPERTY_ARCHIVED = "archived";
  @jakarta.annotation.Nullable
  private Boolean archived = false;

  public FTModelCard() {
  }

  public FTModelCard id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public FTModelCard _object(@jakarta.annotation.Nullable String _object) {
    
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObject(@jakarta.annotation.Nullable String _object) {
    this._object = _object;
  }

  public FTModelCard created(@jakarta.annotation.Nullable Integer created) {
    
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(@jakarta.annotation.Nullable Integer created) {
    this.created = created;
  }

  public FTModelCard ownedBy(@jakarta.annotation.Nullable String ownedBy) {
    
    this.ownedBy = ownedBy;
    return this;
  }

  /**
   * Get ownedBy
   * @return ownedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnedBy() {
    return ownedBy;
  }


  @JsonProperty(JSON_PROPERTY_OWNED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnedBy(@jakarta.annotation.Nullable String ownedBy) {
    this.ownedBy = ownedBy;
  }

  public FTModelCard capabilities(@jakarta.annotation.Nonnull ModelCapabilities capabilities) {
    
    this.capabilities = capabilities;
    return this;
  }

  /**
   * Get capabilities
   * @return capabilities
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CAPABILITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ModelCapabilities getCapabilities() {
    return capabilities;
  }


  @JsonProperty(JSON_PROPERTY_CAPABILITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCapabilities(@jakarta.annotation.Nonnull ModelCapabilities capabilities) {
    this.capabilities = capabilities;
  }

  public FTModelCard name(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }

  public FTModelCard description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public FTModelCard maxContextLength(@jakarta.annotation.Nullable Integer maxContextLength) {
    
    this.maxContextLength = maxContextLength;
    return this;
  }

  /**
   * Get maxContextLength
   * @return maxContextLength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_CONTEXT_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxContextLength() {
    return maxContextLength;
  }


  @JsonProperty(JSON_PROPERTY_MAX_CONTEXT_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxContextLength(@jakarta.annotation.Nullable Integer maxContextLength) {
    this.maxContextLength = maxContextLength;
  }

  public FTModelCard aliases(@jakarta.annotation.Nullable List<String> aliases) {
    
    this.aliases = aliases;
    return this;
  }

  public FTModelCard addAliasesItem(String aliasesItem) {
    if (this.aliases == null) {
      this.aliases = new ArrayList<>();
    }
    this.aliases.add(aliasesItem);
    return this;
  }

  /**
   * Get aliases
   * @return aliases
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALIASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAliases() {
    return aliases;
  }


  @JsonProperty(JSON_PROPERTY_ALIASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAliases(@jakarta.annotation.Nullable List<String> aliases) {
    this.aliases = aliases;
  }

  public FTModelCard deprecation(@jakarta.annotation.Nullable OffsetDateTime deprecation) {
    this.deprecation = JsonNullable.<OffsetDateTime>of(deprecation);
    
    return this;
  }

  /**
   * Get deprecation
   * @return deprecation
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getDeprecation() {
        return deprecation.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DEPRECATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getDeprecation_JsonNullable() {
    return deprecation;
  }
  
  @JsonProperty(JSON_PROPERTY_DEPRECATION)
  public void setDeprecation_JsonNullable(JsonNullable<OffsetDateTime> deprecation) {
    this.deprecation = deprecation;
  }

  public void setDeprecation(@jakarta.annotation.Nullable OffsetDateTime deprecation) {
    this.deprecation = JsonNullable.<OffsetDateTime>of(deprecation);
  }

  public FTModelCard defaultModelTemperature(@jakarta.annotation.Nullable BigDecimal defaultModelTemperature) {
    this.defaultModelTemperature = JsonNullable.<BigDecimal>of(defaultModelTemperature);
    
    return this;
  }

  /**
   * Get defaultModelTemperature
   * @return defaultModelTemperature
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getDefaultModelTemperature() {
        return defaultModelTemperature.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DEFAULT_MODEL_TEMPERATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getDefaultModelTemperature_JsonNullable() {
    return defaultModelTemperature;
  }
  
  @JsonProperty(JSON_PROPERTY_DEFAULT_MODEL_TEMPERATURE)
  public void setDefaultModelTemperature_JsonNullable(JsonNullable<BigDecimal> defaultModelTemperature) {
    this.defaultModelTemperature = defaultModelTemperature;
  }

  public void setDefaultModelTemperature(@jakarta.annotation.Nullable BigDecimal defaultModelTemperature) {
    this.defaultModelTemperature = JsonNullable.<BigDecimal>of(defaultModelTemperature);
  }

  public FTModelCard type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public FTModelCard job(@jakarta.annotation.Nonnull String job) {
    
    this.job = job;
    return this;
  }

  /**
   * Get job
   * @return job
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_JOB)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getJob() {
    return job;
  }


  @JsonProperty(JSON_PROPERTY_JOB)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setJob(@jakarta.annotation.Nonnull String job) {
    this.job = job;
  }

  public FTModelCard root(@jakarta.annotation.Nonnull String root) {
    
    this.root = root;
    return this;
  }

  /**
   * Get root
   * @return root
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRoot() {
    return root;
  }


  @JsonProperty(JSON_PROPERTY_ROOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoot(@jakarta.annotation.Nonnull String root) {
    this.root = root;
  }

  public FTModelCard archived(@jakarta.annotation.Nullable Boolean archived) {
    
    this.archived = archived;
    return this;
  }

  /**
   * Get archived
   * @return archived
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getArchived() {
    return archived;
  }


  @JsonProperty(JSON_PROPERTY_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchived(@jakarta.annotation.Nullable Boolean archived) {
    this.archived = archived;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FTModelCard ftModelCard = (FTModelCard) o;
    return Objects.equals(this.id, ftModelCard.id) &&
        Objects.equals(this._object, ftModelCard._object) &&
        Objects.equals(this.created, ftModelCard.created) &&
        Objects.equals(this.ownedBy, ftModelCard.ownedBy) &&
        Objects.equals(this.capabilities, ftModelCard.capabilities) &&
        equalsNullable(this.name, ftModelCard.name) &&
        equalsNullable(this.description, ftModelCard.description) &&
        Objects.equals(this.maxContextLength, ftModelCard.maxContextLength) &&
        Objects.equals(this.aliases, ftModelCard.aliases) &&
        equalsNullable(this.deprecation, ftModelCard.deprecation) &&
        equalsNullable(this.defaultModelTemperature, ftModelCard.defaultModelTemperature) &&
        Objects.equals(this.type, ftModelCard.type) &&
        Objects.equals(this.job, ftModelCard.job) &&
        Objects.equals(this.root, ftModelCard.root) &&
        Objects.equals(this.archived, ftModelCard.archived);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, created, ownedBy, capabilities, hashCodeNullable(name), hashCodeNullable(description), maxContextLength, aliases, hashCodeNullable(deprecation), hashCodeNullable(defaultModelTemperature), type, job, root, archived);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FTModelCard {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    ownedBy: ").append(toIndentedString(ownedBy)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    maxContextLength: ").append(toIndentedString(maxContextLength)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("    deprecation: ").append(toIndentedString(deprecation)).append("\n");
    sb.append("    defaultModelTemperature: ").append(toIndentedString(defaultModelTemperature)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    job: ").append(toIndentedString(job)).append("\n");
    sb.append("    root: ").append(toIndentedString(root)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

