/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.*;
import org.openapitools.jackson.nullable.JsonNullable;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Objects;

/**
 * GithubRepositoryOut
 */
@JsonPropertyOrder({
  GithubRepositoryOut.JSON_PROPERTY_TYPE,
  GithubRepositoryOut.JSON_PROPERTY_NAME,
  GithubRepositoryOut.JSON_PROPERTY_OWNER,
  GithubRepositoryOut.JSON_PROPERTY_REF,
  GithubRepositoryOut.JSON_PROPERTY_WEIGHT,
  GithubRepositoryOut.JSON_PROPERTY_COMMIT_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class GithubRepositoryOut {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    GITHUB(String.valueOf("github"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type = TypeEnum.GITHUB;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @jakarta.annotation.Nonnull
  private String owner;

  public static final String JSON_PROPERTY_REF = "ref";
  @jakarta.annotation.Nullable
  private JsonNullable<String> ref = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  @jakarta.annotation.Nullable
  private BigDecimal weight = new BigDecimal("1");

  public static final String JSON_PROPERTY_COMMIT_ID = "commit_id";
  @jakarta.annotation.Nonnull
  private String commitId;

  public GithubRepositoryOut() {
  }

  public GithubRepositoryOut type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public GithubRepositoryOut name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public GithubRepositoryOut owner(@jakarta.annotation.Nonnull String owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOwner() {
    return owner;
  }


  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOwner(@jakarta.annotation.Nonnull String owner) {
    this.owner = owner;
  }

  public GithubRepositoryOut ref(@jakarta.annotation.Nullable String ref) {
    this.ref = JsonNullable.<String>of(ref);
    
    return this;
  }

  /**
   * Get ref
   * @return ref
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getRef() {
        return ref.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getRef_JsonNullable() {
    return ref;
  }
  
  @JsonProperty(JSON_PROPERTY_REF)
  public void setRef_JsonNullable(JsonNullable<String> ref) {
    this.ref = ref;
  }

  public void setRef(@jakarta.annotation.Nullable String ref) {
    this.ref = JsonNullable.<String>of(ref);
  }

  public GithubRepositoryOut weight(@jakarta.annotation.Nullable BigDecimal weight) {
    
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * @return weight
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWeight() {
    return weight;
  }


  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(@jakarta.annotation.Nullable BigDecimal weight) {
    this.weight = weight;
  }

  public GithubRepositoryOut commitId(@jakarta.annotation.Nonnull String commitId) {
    
    this.commitId = commitId;
    return this;
  }

  /**
   * Get commitId
   * @return commitId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMMIT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCommitId() {
    return commitId;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCommitId(@jakarta.annotation.Nonnull String commitId) {
    this.commitId = commitId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GithubRepositoryOut githubRepositoryOut = (GithubRepositoryOut) o;
    return Objects.equals(this.type, githubRepositoryOut.type) &&
        Objects.equals(this.name, githubRepositoryOut.name) &&
        Objects.equals(this.owner, githubRepositoryOut.owner) &&
        equalsNullable(this.ref, githubRepositoryOut.ref) &&
        Objects.equals(this.weight, githubRepositoryOut.weight) &&
        Objects.equals(this.commitId, githubRepositoryOut.commitId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, owner, hashCodeNullable(ref), weight, commitId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GithubRepositoryOut {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    commitId: ").append(toIndentedString(commitId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

