/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.jackson.nullable.JsonNullable;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Objects;

/**
 * JobMetadataOut
 */
@JsonPropertyOrder({
  JobMetadataOut.JSON_PROPERTY_EXPECTED_DURATION_SECONDS,
  JobMetadataOut.JSON_PROPERTY_COST,
  JobMetadataOut.JSON_PROPERTY_COST_CURRENCY,
  JobMetadataOut.JSON_PROPERTY_TRAIN_TOKENS_PER_STEP,
  JobMetadataOut.JSON_PROPERTY_TRAIN_TOKENS,
  JobMetadataOut.JSON_PROPERTY_DATA_TOKENS,
  JobMetadataOut.JSON_PROPERTY_ESTIMATED_START_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class JobMetadataOut {
  public static final String JSON_PROPERTY_EXPECTED_DURATION_SECONDS = "expected_duration_seconds";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> expectedDurationSeconds = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_COST = "cost";
  @jakarta.annotation.Nullable
  private JsonNullable<BigDecimal> cost = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_COST_CURRENCY = "cost_currency";
  @jakarta.annotation.Nullable
  private JsonNullable<String> costCurrency = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TRAIN_TOKENS_PER_STEP = "train_tokens_per_step";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> trainTokensPerStep = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_TRAIN_TOKENS = "train_tokens";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> trainTokens = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_DATA_TOKENS = "data_tokens";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> dataTokens = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_ESTIMATED_START_TIME = "estimated_start_time";
  @jakarta.annotation.Nullable
  private JsonNullable<Integer> estimatedStartTime = JsonNullable.<Integer>undefined();

  public JobMetadataOut() {
  }

  public JobMetadataOut expectedDurationSeconds(@jakarta.annotation.Nullable Integer expectedDurationSeconds) {
    this.expectedDurationSeconds = JsonNullable.<Integer>of(expectedDurationSeconds);
    
    return this;
  }

  /**
   * Get expectedDurationSeconds
   * @return expectedDurationSeconds
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getExpectedDurationSeconds() {
        return expectedDurationSeconds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EXPECTED_DURATION_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getExpectedDurationSeconds_JsonNullable() {
    return expectedDurationSeconds;
  }
  
  @JsonProperty(JSON_PROPERTY_EXPECTED_DURATION_SECONDS)
  public void setExpectedDurationSeconds_JsonNullable(JsonNullable<Integer> expectedDurationSeconds) {
    this.expectedDurationSeconds = expectedDurationSeconds;
  }

  public void setExpectedDurationSeconds(@jakarta.annotation.Nullable Integer expectedDurationSeconds) {
    this.expectedDurationSeconds = JsonNullable.<Integer>of(expectedDurationSeconds);
  }

  public JobMetadataOut cost(@jakarta.annotation.Nullable BigDecimal cost) {
    this.cost = JsonNullable.<BigDecimal>of(cost);
    
    return this;
  }

  /**
   * Get cost
   * @return cost
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public BigDecimal getCost() {
        return cost.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getCost_JsonNullable() {
    return cost;
  }
  
  @JsonProperty(JSON_PROPERTY_COST)
  public void setCost_JsonNullable(JsonNullable<BigDecimal> cost) {
    this.cost = cost;
  }

  public void setCost(@jakarta.annotation.Nullable BigDecimal cost) {
    this.cost = JsonNullable.<BigDecimal>of(cost);
  }

  public JobMetadataOut costCurrency(@jakarta.annotation.Nullable String costCurrency) {
    this.costCurrency = JsonNullable.<String>of(costCurrency);
    
    return this;
  }

  /**
   * Get costCurrency
   * @return costCurrency
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getCostCurrency() {
        return costCurrency.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COST_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCostCurrency_JsonNullable() {
    return costCurrency;
  }
  
  @JsonProperty(JSON_PROPERTY_COST_CURRENCY)
  public void setCostCurrency_JsonNullable(JsonNullable<String> costCurrency) {
    this.costCurrency = costCurrency;
  }

  public void setCostCurrency(@jakarta.annotation.Nullable String costCurrency) {
    this.costCurrency = JsonNullable.<String>of(costCurrency);
  }

  public JobMetadataOut trainTokensPerStep(@jakarta.annotation.Nullable Integer trainTokensPerStep) {
    this.trainTokensPerStep = JsonNullable.<Integer>of(trainTokensPerStep);
    
    return this;
  }

  /**
   * Get trainTokensPerStep
   * @return trainTokensPerStep
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getTrainTokensPerStep() {
        return trainTokensPerStep.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRAIN_TOKENS_PER_STEP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTrainTokensPerStep_JsonNullable() {
    return trainTokensPerStep;
  }
  
  @JsonProperty(JSON_PROPERTY_TRAIN_TOKENS_PER_STEP)
  public void setTrainTokensPerStep_JsonNullable(JsonNullable<Integer> trainTokensPerStep) {
    this.trainTokensPerStep = trainTokensPerStep;
  }

  public void setTrainTokensPerStep(@jakarta.annotation.Nullable Integer trainTokensPerStep) {
    this.trainTokensPerStep = JsonNullable.<Integer>of(trainTokensPerStep);
  }

  public JobMetadataOut trainTokens(@jakarta.annotation.Nullable Integer trainTokens) {
    this.trainTokens = JsonNullable.<Integer>of(trainTokens);
    
    return this;
  }

  /**
   * Get trainTokens
   * @return trainTokens
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getTrainTokens() {
        return trainTokens.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRAIN_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTrainTokens_JsonNullable() {
    return trainTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_TRAIN_TOKENS)
  public void setTrainTokens_JsonNullable(JsonNullable<Integer> trainTokens) {
    this.trainTokens = trainTokens;
  }

  public void setTrainTokens(@jakarta.annotation.Nullable Integer trainTokens) {
    this.trainTokens = JsonNullable.<Integer>of(trainTokens);
  }

  public JobMetadataOut dataTokens(@jakarta.annotation.Nullable Integer dataTokens) {
    this.dataTokens = JsonNullable.<Integer>of(dataTokens);
    
    return this;
  }

  /**
   * Get dataTokens
   * @return dataTokens
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getDataTokens() {
        return dataTokens.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DATA_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getDataTokens_JsonNullable() {
    return dataTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_DATA_TOKENS)
  public void setDataTokens_JsonNullable(JsonNullable<Integer> dataTokens) {
    this.dataTokens = dataTokens;
  }

  public void setDataTokens(@jakarta.annotation.Nullable Integer dataTokens) {
    this.dataTokens = JsonNullable.<Integer>of(dataTokens);
  }

  public JobMetadataOut estimatedStartTime(@jakarta.annotation.Nullable Integer estimatedStartTime) {
    this.estimatedStartTime = JsonNullable.<Integer>of(estimatedStartTime);
    
    return this;
  }

  /**
   * Get estimatedStartTime
   * @return estimatedStartTime
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Integer getEstimatedStartTime() {
        return estimatedStartTime.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ESTIMATED_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getEstimatedStartTime_JsonNullable() {
    return estimatedStartTime;
  }
  
  @JsonProperty(JSON_PROPERTY_ESTIMATED_START_TIME)
  public void setEstimatedStartTime_JsonNullable(JsonNullable<Integer> estimatedStartTime) {
    this.estimatedStartTime = estimatedStartTime;
  }

  public void setEstimatedStartTime(@jakarta.annotation.Nullable Integer estimatedStartTime) {
    this.estimatedStartTime = JsonNullable.<Integer>of(estimatedStartTime);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobMetadataOut jobMetadataOut = (JobMetadataOut) o;
    return equalsNullable(this.expectedDurationSeconds, jobMetadataOut.expectedDurationSeconds) &&
        equalsNullable(this.cost, jobMetadataOut.cost) &&
        equalsNullable(this.costCurrency, jobMetadataOut.costCurrency) &&
        equalsNullable(this.trainTokensPerStep, jobMetadataOut.trainTokensPerStep) &&
        equalsNullable(this.trainTokens, jobMetadataOut.trainTokens) &&
        equalsNullable(this.dataTokens, jobMetadataOut.dataTokens) &&
        equalsNullable(this.estimatedStartTime, jobMetadataOut.estimatedStartTime);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(expectedDurationSeconds), hashCodeNullable(cost), hashCodeNullable(costCurrency), hashCodeNullable(trainTokensPerStep), hashCodeNullable(trainTokens), hashCodeNullable(dataTokens), hashCodeNullable(estimatedStartTime));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobMetadataOut {\n");
    sb.append("    expectedDurationSeconds: ").append(toIndentedString(expectedDurationSeconds)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    costCurrency: ").append(toIndentedString(costCurrency)).append("\n");
    sb.append("    trainTokensPerStep: ").append(toIndentedString(trainTokensPerStep)).append("\n");
    sb.append("    trainTokens: ").append(toIndentedString(trainTokens)).append("\n");
    sb.append("    dataTokens: ").append(toIndentedString(dataTokens)).append("\n");
    sb.append("    estimatedStartTime: ").append(toIndentedString(estimatedStartTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

