/*
 * Mistral AI API
 * Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.arhs.ai.poc.mistral.client.model;

import com.fasterxml.jackson.annotation.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ReferenceChunk
 */
@JsonPropertyOrder({
  ReferenceChunk.JSON_PROPERTY_REFERENCE_IDS,
  ReferenceChunk.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T14:53:13.544788800+01:00[Europe/Berlin]", comments = "Generator version: 7.10.0")
public class ReferenceChunk {
  public static final String JSON_PROPERTY_REFERENCE_IDS = "reference_ids";
  @jakarta.annotation.Nonnull
  private List<Integer> referenceIds = new ArrayList<>();

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    REFERENCE(String.valueOf("reference"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private TypeEnum type = TypeEnum.REFERENCE;

  public ReferenceChunk() {
  }

  public ReferenceChunk referenceIds(@jakarta.annotation.Nonnull List<Integer> referenceIds) {
    
    this.referenceIds = referenceIds;
    return this;
  }

  public ReferenceChunk addReferenceIdsItem(Integer referenceIdsItem) {
    if (this.referenceIds == null) {
      this.referenceIds = new ArrayList<>();
    }
    this.referenceIds.add(referenceIdsItem);
    return this;
  }

  /**
   * Get referenceIds
   * @return referenceIds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REFERENCE_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Integer> getReferenceIds() {
    return referenceIds;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferenceIds(@jakarta.annotation.Nonnull List<Integer> referenceIds) {
    this.referenceIds = referenceIds;
  }

  public ReferenceChunk type(@jakarta.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceChunk referenceChunk = (ReferenceChunk) o;
    return Objects.equals(this.referenceIds, referenceChunk.referenceIds) &&
        Objects.equals(this.type, referenceChunk.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceIds, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceChunk {\n");
    sb.append("    referenceIds: ").append(toIndentedString(referenceIds)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

